[repository]
name = "hyprWorkspaceLayouts"
authors = ["Zakk"]

[hyprWorkspaceLayouts]
description = "Use different layouts on workspaces"
authors = ["Zakk"]
output = "workspaceLayoutPlugin.so"
build = [
	"make all"
]
